# encoding: utf-8
require 'countries'

module CountrySelect
  @@use_iso_codes = false
  def self.use_iso_codes
    @@use_iso_codes
  end
  def self.use_iso_codes=(use_iso_codes)
    @@use_iso_codes = use_iso_codes
  end

  unless const_defined?("COUNTRIES")
    COUNTRIES =  [{name: "Afghanistan", alternatives: "AF افغانستان"},
                  {name: "Åland Islands", alternatives: "AX Aaland Aland", relevancy_booster: "0.5"},
                  {name: "Albania", alternatives: "AL"},
                  {name: "Algeria", alternatives: "DZ الجزائر"},
                  {name: "American Samoa", alternatives: "AS", relevancy_booster: "0.5"},
                  {name: "Andorra", alternatives: "AD", relevancy_booster: "0.5"},
                  {name: "Angola", alternatives: "AO"},
                  {name: "Anguilla", alternatives: "AI", relevancy_booster: "0.5"},
                  {name: "Antarctica", alternatives: "AQ", relevancy_booster: "0.5"},
                  {name: "Antigua And Barbuda", alternatives: "AG", relevancy_booster: "0.5"},
                  {name: "Argentina", alternatives: "AR"},
                  {name: "Armenia", alternatives: "AM Հայաստան"},
                  {name: "Aruba", alternatives: "AW", relevancy_booster: "0.5"},
                  {name: "Australia", alternatives: "AU", relevancy_booster: "1.5"},
                  {name: "Austria", alternatives: "AT Österreich Osterreich Oesterreich "},
                  {name: "Azerbaijan", alternatives: "AZ"},
                  {name: "Bahamas", alternatives: "BS"},
                  {name: "Bahrain", alternatives: "BH البحرين"},
                  {name: "Bangladesh", alternatives: "BD বাংলাদেশ", relevancy_booster: "2"},
                  {name: "Barbados", alternatives: "BB"},
                  {name: "Belarus", alternatives: "BY Беларусь"},
                  {name: "Belgium", alternatives: "BE België Belgie Belgien Belgique", relevancy_booster: "1.5"},
                  {name: "Belize", alternatives: "BZ"},
                  {name: "Benin", alternatives: "BJ"},
                  {name: "Bermuda", alternatives: "BM", relevancy_booster: "0.5"},
                  {name: "Bhutan", alternatives: "BT भूटान"},
                  {name: "Bolivia", alternatives: "BO"},
                  {name: "Bonaire, Sint Eustatius and Saba", alternatives: "BQ"},
                  {name: "Bosnia and Herzegovina", alternatives: "BA Босна и Херцеговина"},
                  {name: "Botswana", alternatives: "BW"},
                  {name: "Bouvet Island", alternatives: "BV"},
                  {name: "Brazil", alternatives: "BR Brasil", relevancy_booster: "2"},
                  {name: "British Indian Ocean Territory", alternatives: "IO"},
                  {name: "Brunei Darussalam", alternatives: "BN"},
                  {name: "Bulgaria", alternatives: "BG България"},
                  {name: "Burkina Faso", alternatives: "BF"},
                  {name: "Burundi", alternatives: "BI"},
                  {name: "Cambodia", alternatives: "KH កម្ពុជា"},
                  {name: "Cameroon", alternatives: "CM"},
                  {name: "Canada", alternatives: "CA", relevancy_booster: "2"},
                  {name: "Cape Verde", alternatives: "CV Cabo"},
                  {name: "Cayman Islands", alternatives: "KY", relevancy_booster: "0.5"},
                  {name: "Central African Republic", alternatives: "CF"},
                  {name: "Chad", alternatives: "TD تشاد‎ Tchad"},
                  {name: "Chile", alternatives: "CL"},
                  {name: "China", relevancy_booster: "3.5", alternatives: "CN Zhongguo Zhonghua Peoples Republic 中国/中华"},
                  {name: "Christmas Island", alternatives: "CX", relevancy_booster: "0.5"},
                  {name: "Cocos (Keeling) Islands", alternatives: "CC", relevancy_booster: "0.5"},
                  {name: "Colombia", alternatives: "CO"},
                  {name: "Comoros", alternatives: "KM جزر القمر"},
                  {name: "Congo", alternatives: "CG"},
                  {name: "Congo, the Democratic Republic of the", alternatives: "CD Congo-Brazzaville Repubilika ya Kongo"},
                  {name: "Cook Islands", alternatives: "CK", relevancy_booster: "0.5"},
                  {name: "Costa Rica", alternatives: "CR"},
                  {name: "Côte d'Ivoire", alternatives: "CI Cote dIvoire"},
                  {name: "Croatia", alternatives: "HR Hrvatska"},
                  {name: "Cuba", alternatives: "CU"},
                  {name: "Curaçao", alternatives: "CW Curacao"},
                  {name: "Cyprus", alternatives: "CY Κύπρος Kýpros Kıbrıs"},
                  {name: "Czech Republic", alternatives: "CZ Česká Ceska"},
                  {name: "Denmark", alternatives: "DK Danmark", relevancy_booster: "1.5"},
                  {name: "Djibouti", alternatives: "DJ جيبوتي‎ Jabuuti Gabuuti"},
                  {name: "Dominica", alternatives: "DM Dominique", relevancy_booster: "0.5"},
                  {name: "Dominican Republic", alternatives: "DO"},
                  {name: "Ecuador", alternatives: "EC"},
                  {name: "Egypt", alternatives: "EG", relevancy_booster: "1.5"},
                  {name: "El Salvador", alternatives: "SV"},
                  {name: "Equatorial Guinea", alternatives: "GQ"},
                  {name: "Eritrea", alternatives: "ER إرتريا ኤርትራ"},
                  {name: "Estonia", alternatives: "EE Eesti"},
                  {name: "Ethiopia", alternatives: "ET ኢትዮጵያ"},
                  {name: "Falkland Islands (Malvinas)", alternatives: "FK", relevancy_booster: "0.5"},
                  {name: "Faroe Islands", alternatives: "FO Føroyar Færøerne", relevancy_booster: "0.5"},
                  {name: "Fiji", alternatives: "FJ Viti फ़िजी"},
                  {name: "Finland", alternatives: "FI Suomi"},
                  {name: "France", alternatives: "FR République française", relevancy_booster: "2.5"},
                  {name: "French Guiana", alternatives: "GF"},
                  {name: "French Polynesia", alternatives: "PF Polynésie française"},
                  {name: "French Southern Territories", alternatives: "TF"},
                  {name: "Gabon", alternatives: "GA République Gabonaise"},
                  {name: "Gambia", alternatives: "GM"},
                  {name: "Georgia", alternatives: "GE საქართველო"},
                  {name: "Germany", alternatives: "DE Bundesrepublik Deutschland", relevancy_booster: "3"},
                  {name: "Ghana", alternatives: "GH"},
                  {name: "Gibraltar", alternatives: "GI", relevancy_booster: "0.5"},
                  {name: "Greece", alternatives: "GR Ελλάδα", relevancy_booster: "1.5"},
                  {name: "Greenland", alternatives: "GL grønland", relevancy_booster: "0.5"},
                  {name: "Grenada", alternatives: "GD"},
                  {name: "Guadeloupe", alternatives: "GP"},
                  {name: "Guam", alternatives: "GU"},
                  {name: "Guatemala", alternatives: "GT"},
                  {name: "Guernsey", alternatives: "GG", relevancy_booster: "0.5"},
                  {name: "Guinea", alternatives: "GN"},
                  {name: "Guinea-Bissau", alternatives: "GW"},
                  {name: "Guyana", alternatives: "GY"},
                  {name: "Haiti", alternatives: "HT"},
                  {name: "Heard Island and McDonald Islands", alternatives: "HM"},
                  {name: "Holy See (Vatican City State)", alternatives: "VA", relevancy_booster: "0.5"},
                  {name: "Honduras", alternatives: "HN"},
                  {name: "Hong Kong", alternatives: "HK 香港"},
                  {name: "Hungary", alternatives: "HU Magyarország"},
                  {name: "Iceland", alternatives: "IS Island"},
                  {name: "India", alternatives: "IN भारत गणराज्य Hindustan", relevancy_booster: "3"},
                  {name: "Indonesia", alternatives: "ID", relevancy_booster: "2"},
                  {name: "Iran, Islamic Republic of", alternatives: "IR ایران"},
                  {name: "Iraq", alternatives: "IQ العراق‎"},
                  {name: "Ireland", alternatives: "IE Éire", relevancy_booster: "1.2"},
                  {name: "Isle of Man", alternatives: "IM", relevancy_booster: "0.5"},
                  {name: "Israel", alternatives: "IL إسرائيل ישראל"},
                  {name: "Italy", alternatives: "IT Italia", relevancy_booster: "2"},
                  {name: "Jamaica", alternatives: "JM"},
                  {name: "Japan", alternatives: "JP Nippon Nihon 日本", relevancy_booster: "2.5"},
                  {name: "Jersey", alternatives: "JE", relevancy_booster: "0.5"},
                  {name: "Jordan", alternatives: "JO الأردن"},
                  {name: "Kazakhstan", alternatives: "KZ Қазақстан Казахстан"},
                  {name: "Kenya", alternatives: "KE"},
                  {name: "Kiribati", alternatives: "KI"},
                  {name: "Korea, Democratic People's Republic of", alternatives: "KP North Korea"},
                  {name: "Korea, Republic of", alternatives: "KR South Korea", relevancy_booster: "1.5"},
                  {name: "Kuwait", alternatives: "KW الكويت"},
                  {name: "Kyrgyzstan", alternatives: "KG Кыргызстан"},
                  {name: "Lao People's Democratic Republic", alternatives: "LA"},
                  {name: "Latvia", alternatives: "LV Latvija"},
                  {name: "Lebanon", alternatives: "LB لبنان"},
                  {name: "Lesotho", alternatives: "LS"},
                  {name: "Liberia", alternatives: "LR"},
                  {name: "Libyan Arab Jamahiriya", alternatives: "LY ليبيا"},
                  {name: "Liechtenstein", alternatives: "LI"},
                  {name: "Lithuania", alternatives: "LT Lietuva"},
                  {name: "Luxembourg", alternatives: "LU"},
                  {name: "Macao", alternatives: "MO"},
                  {name: "Macedonia, The Former Yugoslav Republic Of", alternatives: "MK Македонија"},
                  {name: "Madagascar", alternatives: "MG Madagasikara"},
                  {name: "Malawi", alternatives: "MW"},
                  {name: "Malaysia", alternatives: "MY"},
                  {name: "Maldives", alternatives: "MV"},
                  {name: "Mali", alternatives: "ML"},
                  {name: "Malta", alternatives: "MT"},
                  {name: "Marshall Islands", alternatives: "MH", relevancy_booster: "0.5"},
                  {name: "Martinique", alternatives: "MQ"},
                  {name: "Mauritania", alternatives: "MR الموريتانية"},
                  {name: "Mauritius", alternatives: "MU"},
                  {name: "Mayotte", alternatives: "YT"},
                  {name: "Mexico", alternatives: "MX Mexicanos", relevancy_booster: "1.5"},
                  {name: "Micronesia, Federated States of", alternatives: "FM"},
                  {name: "Moldova, Republic of", alternatives: "MD"},
                  {name: "Monaco", alternatives: "MC"},
                  {name: "Mongolia", alternatives: "MN Mongγol ulus Монгол улс"},
                  {name: "Montenegro", alternatives: "ME"},
                  {name: "Montserrat", alternatives: "MS", relevancy_booster: "0.5"},
                  {name: "Morocco", alternatives: "MA المغرب"},
                  {name: "Mozambique", alternatives: "MZ Moçambique"},
                  {name: "Myanmar", alternatives: "MM"},
                  {name: "Namibia", alternatives: "NA Namibië"},
                  {name: "Nauru", alternatives: "NR Naoero", relevancy_booster: "0.5"},
                  {name: "Nepal", alternatives: "NP नेपाल"},
                  {name: "Netherlands", alternatives: "NL Holland Nederland", relevancy_booster: "1.5"},
                  {name: "New Caledonia", alternatives: "NC", relevancy_booster: "0.5"},
                  {name: "New Zealand", alternatives: "NZ Aotearoa"},
                  {name: "Nicaragua", alternatives: "NI"},
                  {name: "Niger", alternatives: "NE Nijar"},
                  {name: "Nigeria", alternatives: "NG Nijeriya Naíjíríà", relevancy_booster: "1.5"},
                  {name: "Niue", alternatives: "NU", relevancy_booster: "0.5"},
                  {name: "Norfolk Island", alternatives: "NF", relevancy_booster: "0.5"},
                  {name: "Northern Mariana Islands", alternatives: "MP", relevancy_booster: "0.5"},
                  {name: "Norway", alternatives: "NO Norge Noreg", relevancy_booster: "1.5"},
                  {name: "Oman", alternatives: "OM عمان"},
                  {name: "Pakistan", alternatives: "PK پاکستان", relevancy_booster: "2"},
                  {name: "Palau", alternatives: "PW", relevancy_booster: "0.5"},
                  {name: "Palestinian Territory, Occupied", alternatives: "PS فلسطين"},
                  {name: "Panama", alternatives: "PA"},
                  {name: "Papua New Guinea", alternatives: "PG"},
                  {name: "Paraguay", alternatives: "PY"},
                  {name: "Peru", alternatives: "PE"},
                  {name: "Philippines", alternatives: "PH Pilipinas", relevancy_booster: "1.5"},
                  {name: "Pitcairn", alternatives: "PN", relevancy_booster: "0.5"},
                  {name: "Poland", alternatives: "PL Polska", relevancy_booster: "1.25"},
                  {name: "Portugal", alternatives: "PT Portuguesa", relevancy_booster: "1.5"},
                  {name: "Puerto Rico", alternatives: "PR"},
                  {name: "Qatar", alternatives: "QA قطر"},
                  {name: "Réunion", alternatives: "RE Reunion"},
                  {name: "Romania", alternatives: "RO Rumania Roumania România"},
                  {name: "Russian Federation", alternatives: "RU Rossiya Российская Россия", relevancy_booster: "2.5"},
                  {name: "Rwanda", alternatives: "RW"},
                  {name: "Saint Barthélemy", alternatives: "BL St. Barthelemy"},
                  {name: "Saint Helena", alternatives: "SH St."},
                  {name: "Saint Kitts and Nevis", alternatives: "KN St."},
                  {name: "Saint Lucia", alternatives: "LC St."},
                  {name: "Saint Martin (French Part)", alternatives: "MF St."},
                  {name: "Saint Pierre and Miquelon", alternatives: "PM St."},
                  {name: "Saint Vincent and the Grenadines", alternatives: "VC St."},
                  {name: "Samoa", alternatives: "WS"},
                  {name: "San Marino", alternatives: "SM"},
                  {name: "Sao Tome and Principe", alternatives: "ST"},
                  {name: "Saudi Arabia", alternatives: "SA السعودية"},
                  {name: "Senegal", alternatives: "SN Sénégal"},
                  {name: "Serbia", alternatives: "RS Србија Srbija"},
                  {name: "Seychelles", alternatives: "SC", relevancy_booster: "0.5"},
                  {name: "Sierra Leone", alternatives: "SL"},
                  {name: "Singapore", alternatives: "SG Singapura  சிங்கப்பூர் குடியரசு 新加坡共和国"},
                  {name: "Sint Maarten (Dutch Part)", alternatives: "SX"},
                  {name: "Slovakia", alternatives: "SK Slovenská Slovensko"},
                  {name: "Slovenia", alternatives: "SI Slovenija"},
                  {name: "Solomon Islands", alternatives: "SB"},
                  {name: "Somalia", alternatives: "SO الصومال"},
                  {name: "South Africa", alternatives: "ZA RSA Suid-Afrika"},
                  {name: "South Georgia and the South Sandwich Islands", alternatives: "GS"},
                  {name: "South Sudan", alternatives: "SS"},
                  {name: "Spain", alternatives: "ES España", relevancy_booster: "2"},
                  {name: "Sri Lanka", alternatives: "LK ශ්‍රී ලංකා இலங்கை Ceylon"},
                  {name: "Sudan", alternatives: "SD السودان"},
                  {name: "Suriname", alternatives: "SR शर्नम् Sarnam Sranangron"},
                  {name: "Svalbard and Jan Mayen", alternatives: "SJ", relevancy_booster: "0.5"},
                  {name: "Swaziland", alternatives: "SZ weSwatini Swatini Ngwane"},
                  {name: "Sweden", alternatives: "SE Sverige", relevancy_booster: "1.5"},
                  {name: "Switzerland", alternatives: "CH Swiss Confederation Schweiz Suisse Svizzera Svizra", relevancy_booster: "1.5"},
                  {name: "Syrian Arab Republic", alternatives: "SY Syria سورية"},
                  {name: "Taiwan", alternatives: "TW 台灣 臺灣"},
                  {name: "Tajikistan", alternatives: "TJ Тоҷикистон Toçikiston"},
                  {name: "Tanzania, United Republic of", alternatives: "TZ"},
                  {name: "Thailand", alternatives: "TH ประเทศไทย Prathet Thai"},
                  {name: "Timor-Leste", alternatives: "TL"},
                  {name: "Togo", alternatives: "TG Togolese"},
                  {name: "Tokelau", alternatives: "TK", relevancy_booster: "0.5"},
                  {name: "Tonga", alternatives: "TO"},
                  {name: "Trinidad and Tobago", alternatives: "TT"},
                  {name: "Tunisia", alternatives: "TN تونس"},
                  {name: "Turkey", alternatives: "TR Türkiye Turkiye"},
                  {name: "Turkmenistan", alternatives: "TM Türkmenistan"},
                  {name: "Turks and Caicos Islands", alternatives: "TC", relevancy_booster: "0.5"},
                  {name: "Tuvalu", alternatives: "TV", relevancy_booster: "0.5"},
                  {name: "Uganda", alternatives: "UG"},
                  {name: "Ukraine", alternatives: "UA Ukrayina Україна"},
                  {name: "United Arab Emirates", alternatives: "AE UAE الإمارات"},
                  {name: "United Kingdom", alternatives: "GB Great Britain England UK Wales Scotland Northern Ireland", relevancy_booster: "2.5"},
                  {name: "United States", relevancy_booster: "3.5", alternatives: "US USA United States of America"},
                  {name: "United States Minor Outlying Islands", alternatives: "UM"},
                  {name: "Uruguay", alternatives: "UY"},
                  {name: "Uzbekistan", alternatives: "UZ Ўзбекистон O'zbekstan O‘zbekiston"},
                  {name: "Vanuatu", alternatives: "VU"},
                  {name: "Venezuela", alternatives: "VE"},
                  {name: "Vietnam", alternatives: "VN Việt Nam", relevancy_booster: "1.5"},
                  {name: "Virgin Islands, British", alternatives: "VG", relevancy_booster: "0.5"},
                  {name: "Virgin Islands, U.S.", alternatives: "VI", relevancy_booster: "0.5"},
                  {name: "Wallis and Futuna", alternatives: "WF", relevancy_booster: "0.5"},
                  {name: "Western Sahara", alternatives: "EH لصحراء الغربية"},
                  {name: "Yemen", alternatives: "YE اليمن"},
                  {name: "Zambia", alternatives: "ZM"},
                  {name: "Zimbabwe", alternatives: "ZW"}]
  end

  ISO_COUNTRIES_FOR_SELECT = COUNTRIES unless const_defined?("ISO_COUNTRIES_FOR_SELECT")
  COUNTRIES_FOR_SELECT = COUNTRIES unless const_defined?("COUNTRIES_FOR_SELECT")
end
